// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAih_jip7xeZqbnOBNEjGgn5hG4khYGyLs',
    appId: '1:513284884013:web:3eeaff3c618364997e9aa4',
    messagingSenderId: '513284884013',
    projectId: 'test-54071',
    authDomain: 'test-54071.firebaseapp.com',
    storageBucket: 'test-54071.appspot.com',
    measurementId: 'G-B9LYY25ZLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0XX6wwLK1lMJNdyJu_a-akYew1hqUVgM',
    appId: '1:513284884013:android:8f0879d8dc5a447d7e9aa4',
    messagingSenderId: '513284884013',
    projectId: 'test-54071',
    storageBucket: 'test-54071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5MZgLGn6PcRtyYI-rVRzG-TtWlchXksg',
    appId: '1:513284884013:ios:1eedcba0b7925e607e9aa4',
    messagingSenderId: '513284884013',
    projectId: 'test-54071',
    storageBucket: 'test-54071.appspot.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5MZgLGn6PcRtyYI-rVRzG-TtWlchXksg',
    appId: '1:513284884013:ios:a95e6284bd28f8bb7e9aa4',
    messagingSenderId: '513284884013',
    projectId: 'test-54071',
    storageBucket: 'test-54071.appspot.com',
    iosBundleId: 'com.example.firebaseSample.RunnerTests',
  );
}
